name: 'Build Rsbuild'
description: 'Checkout, build rsbuild'
inputs:
  repository:
    description: 'The rsbuild repository to use'
    required: true
    default: 'web-infra-dev/rsbuild'
  path:
    description: 'Destination path to the rsbuild repository'
    required: true
    default: 'workspace/rsbuild'
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: true
    default: 'main'
  node-version:
    description: 'The version of Node.js to set up'
    required: true
    default: '18'
outputs:
  artifact-name:
    description: 'The name of the uploaded artifact'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - shell: bash
      name: Install package manager
      run: |
        npm install -g corepack@0.24.1
        echo "Corepack version: $(corepack --version)"
        corepack enable

    - name: Checkout Rsbuild repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        path: ${{ inputs.path }}
        ref: ${{ inputs.ref }}
    - name: Build Rsbuild
      shell: bash
      run: |
        cd ${{ inputs.path }}
        pnpm i
        pnpm run build
