name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  get-runner-labels:
    name: Get Runner Labels
    uses: ./.github/workflows/get-runner-labels.yml

  ci:
    needs: [get-runner-labels]
    strategy:
      matrix:
        include:
          - suite: modernjs
            os: ubuntu-latest
				  - suite: plugins
            os: ubuntu-latest
          - suite: rspress
            os: ubuntu-latest
          - suite: examples
            os: ubuntu-latest
          - suite: rslib
            os: ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.suite }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-rsbuild
      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - run: >-
          pnpm tsx ecosystem-ci.ts
          run-suites
          ${{ matrix.suite }}
