# integration tests for rsbuild ecosystem - run from pr comments
name: rsbuild-ecosystem-ci-from-commit

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

on:
  workflow_dispatch:
    inputs:
      commitSHA:
        description: "commit sha"
        required: true
        type: string
      repo:
        description: "rsbuild repository to use"
        required: true
        type: string
        default: "web-infra-dev/rsbuild"
      suite:
        description: "testsuite to run. runs all testsuits when `-`."
        required: false
        type: choice
        options:
          - "-"
          - modernjs
          - plugins
          - rspress
          - rslib
          - examples
      suiteRefType:
        description: "type of suite ref to use"
        required: true
        type: choice
        options:
          - precoded
          - branch
          - tag
          - commit
        default: "precoded"
      suiteRef:
        description: "suite ref to use"
        required: true
        type: string
        default: "precoded"

jobs:
  execute-selected-suite:
    runs-on: ubuntu-latest
    if: "inputs.suite != '-'"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-rsbuild
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.commitSHA }}
      - run: pnpm i --frozen-lockfile
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - run: >-
          pnpm tsx ecosystem-ci.ts
          run-suites
          --suite-${{ inputs.suiteRefType }} ${{ inputs.suiteRef }}
          ${{ inputs.suite }}

  execute-all:
    if: "inputs.suite == '-'"
    strategy:
      matrix:
        include:
          - suite: modernjs
            os: ubuntu-latest
          - suite: plugins
            os: ubuntu-latest
          - suite: rspress
            os: ubuntu-latest
          - suite: rslib
            os: ubuntu-latest
          - suite: examples
            os: ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: execute-all (${{ matrix.suite }})
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
      - uses: ./.github/actions/build-rsbuild
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.commitSHA }}
      - run: pnpm i --frozen-lockfile
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - run: >-
          pnpm tsx ecosystem-ci.ts
          run-suites
          ${{ matrix.suite }}

  update-comment:
    runs-on: ubuntu-latest
    needs: [execute-selected-suite, execute-all]
    if: always()
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ECOSYSTEM_CI_ACCESS_TOKEN }}
          script: |
            const { data: { jobs } } = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
              per_page: 100
            });

            const selectedSuite = context.payload.inputs.suite
            let result
            if (selectedSuite !== "-") {
              const { conclusion, html_url } = jobs.find(job => job.name === "execute-selected-suite")
              result = [{ suite: `${selectedSuite} ${context.payload.inputs.suiteRefType} ${context.payload.inputs.suiteRef}`, conclusion, link: html_url }]
            } else {
              result = jobs
                .filter(job => job.name.startsWith('execute-all '))
                .map(job => {
                  const suite = job.name.replace(/^execute-all \(([^)]+)\)$/, "$1")
                  return { suite, conclusion: job.conclusion, link: job.html_url }
                })
            }

            const url = `${context.serverUrl}//${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            const urlLink = `[Open](${url})`

            const conclusionEmoji = {
              success: ":white_check_mark:",
              failure: ":x:",
              cancelled: ":stop_button:"
            }

            const body = `
            📝 Ran ecosystem CI: ${urlLink}

            | suite | result |
            |-------|--------|
            ${result.map(r => `| [${r.suite}](${r.link}) | ${conclusionEmoji[r.conclusion]} ${r.conclusion} |`).join("\n")}
            `

            await github.rest.repos.createCommitComment({
              commit_sha: context.payload.inputs.commitSHA,
              owner: 'web-infra-dev',
              repo: 'rsbuild',
              body
            })

            return `https://github.com/web-infra-dev/rsbuild/commit/${context.payload.inputs.commitSHA}#comments`
